export { default as Navbar } from './Navbar'
export { default as Homepage } from './Homepage'
export { default as News } from './News'
export { default as Exch } from './Exch'
export { default as Profile } from './Profile'
export {default as Cryptocurrencies} from './Cryptocurrencies'
